name: 'Terraform CI/CD'

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  terraform-dev:
    name: 'Deploy DEV Environment'
    runs-on: ubuntu-latest
    
    # Só roda o Job do DEV se: for Push na branch development OU PR para branch development
    if: github.ref == 'refs/heads/development' || github.base_ref == 'development'
    
    # Injetando as credenciais via Secrets do GitHub
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        working-directory: ./dev

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Format
      run: terraform fmt -check
      continue-on-error: true

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan -out=tfplan

    - name: Terraform Apply (DEV)
      # Só aplica automaticamente no DEV se for push/merge na branch DEVELOPMENT
      if: github.ref == 'refs/heads/development' && github.event_name == 'push'
      run: terraform apply -auto-approve

  terraform-prod:
    name: 'Deploy PROD Environment'
    runs-on: ubuntu-latest
    environment: production

    # Só roda o Job do PROD se: for Push na branch main OU PR para branch main
    if: github.ref == 'refs/heads/main' || github.base_ref == 'main'
    
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        working-directory: ./prod

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_wrapper: false

    - name: Terraform Init
      run: terraform init

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      if: github.event_name == 'pull_request'
      run: terraform plan -out=tfplan

    - name: Terraform Apply (PROD)
      # Só aplica automaticamente no PROD se for push/merge na branch MAIN
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
